name: angular_auth
description: AngularDart part of auth bloc example
version: 0.1.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  angular: ^5.3.0
  angular_components: ^0.13.0
  angular_bloc: ^3.0.0
  angular_router: ^2.0.0-alpha
  core_auth:
    path: ../core_auth

dev_dependencies:
  build_runner: ">=1.6.2 <2.0.0"
  build_web_compilers: ">=1.2.0 <3.0.0"