name: core_auth
description: Shared Code between AngularDart and Flutter
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  meta: ^1.1.6
  bloc: ^3.0.0
  equatable: ^1.0.0
  http: ^0.12.0
